### DISCUSSION TITLE
PSA: Make the images (or other embeds?) left aligned instead of centered

### DISCUSSION THREAD

**Discussion by TheBestPessimist** [Seniblue/Underwater#32] [General]
```css
/*
Make images left aligned
 */
.image-embed > img {
    margin-inline: 0;
}

```
